spring.application.name=ms-campuslab-bff

server.port=${SERVER_PORT:8080}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${AZURE_AUDIENCE}

services.catalog.url=${CATALOG_SERVICE_URL:http://localhost:8082}

services.bookings.url=${BOOKINGS_SERVICE_URL:http://localhost:8081}