spring.application.name=bff

server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI}

spring.security.oauth2.resourceserver.jwt.audiences=api://<API_CLIENT_ID>



service.catalog.url=${CATALOG_SERVICE_URL:http://localhost:8082}
service.booking.url=${BOOKING_SERVICE_URL:http://localhost:8081}
